version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx."
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo "Building Ignix Server..."
      - cp index.html /var/www/html/  #cp 

  post_build:
    commands:
      - echo "Running post-build steps..."
      - echo Configuring NGINX
      - echo "Build successful!"

artifacts:
  files:
    - '**/*'
  
